package Biblioteca;

/**
* Biblioteca/GestionBibliotecaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Biblioteca.idl
* jueves 3 de abril de 2025 17H01' CEST
*/


// Define la interfaz para el sistema de gestión de la biblioteca
public final class GestionBibliotecaHolder implements org.omg.CORBA.portable.Streamable
{
  public Biblioteca.GestionBiblioteca value = null;

  public GestionBibliotecaHolder ()
  {
  }

  public GestionBibliotecaHolder (Biblioteca.GestionBiblioteca initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Biblioteca.GestionBibliotecaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Biblioteca.GestionBibliotecaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Biblioteca.GestionBibliotecaHelper.type ();
  }

}
