package Biblioteca;


/**
* Biblioteca/GestionBiblioteca.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Biblioteca.idl
* jueves 3 de abril de 2025 17H01' CEST
*/


// Define la interfaz para el sistema de gestión de la biblioteca
public interface GestionBiblioteca extends GestionBibliotecaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionBiblioteca
